export const floors = [
  {
    id: 1,
    rooms: [
      { number: 101, beds: [true, true, true], isPrivate:true, price: 150, packedid: "", priceBed:50 },
      { number: 102, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 103, beds: [true, true, true], isPrivate:true, price: 150, packedid: "", priceBed:50 },
      { number: 104, beds: [true, true, true], isPrivate:false, price: 150, packedid: "Natal", priceBed:50 },
      { number: 105, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 106, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 107, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 108, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 109, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 110, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 111, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 112, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 113, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 114, beds: [true, true, true], isPrivate:true, price: 150, packedid: "", priceBed:50 },
      { number: 115, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 116, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 117, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 118, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 119, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 120, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 121, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 122, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 123, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 124, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 125, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 126, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 127, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 128, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 129, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 130, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 131, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 132, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 133, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 134, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 135, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 136, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 137, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 138, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 139, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 140, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 141, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 142, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 143, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 144, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 145, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 146, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 147, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 148, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 149, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 150, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 151, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 152, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 153, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 154, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 155, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 158, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 158, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 158, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 158, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 158, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 158, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 156, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 157, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 158, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 159, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 160, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
    ]
  },

  {
    id: 2,
    rooms: [
      { number: 201, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 202, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 203, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 204, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 205, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 206, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 207, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 208, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 209, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 210, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },

    ]
  },

  {
    id: 3,
    rooms: [
      { number: 301, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50},
      { number: 302, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 303, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 304, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 305, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 306, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 307, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 308, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 309, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
      { number: 310, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },

    ]
  },
  {
  id: 4,
  rooms: [
    { number: 401, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50},
    { number: 402, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
    { number: 403, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
    { number: 404, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
    { number: 405, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
    { number: 406, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50},
    { number: 407, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
    { number: 408, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
    { number: 409, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
    { number: 410, beds: [true, true, true], isPrivate:false, price: 150, packedid: "", priceBed:50 },
  ]
  }
]
